config/routes.rb
Rails.application.routes.draw do
  post '/articles/:id/comments', to: 'posts#create_comment' , as: 'create_comment'
  get 'accounts/signup', to: 'accounts#signup'
  get 'accounts/login', to: 'accounts#login'
  post 'login_method', to: 'accounts#login_method'
  get 'logout_method', to: 'accounts#logout_method'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'articles/lll', to: 'articles#lll'
  # post '/login', to: 'users#login', as: 'login'
  # Defines the root path route ("/")
  root "articles#index"
  # root "accounts#login"
  resources :articles 
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
    has_secure_password
    attr_accessor :verification_code
    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true

    enum role: { Manager: '2', User: '1', guest: '0' }






end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  # Article模型 属于 Account模型
  belongs_to :account
  # Article 对象可以拥有多个 Comment 对象
  has_many :comments
  # 对 Article 的 title 属性进行验证，确保title属性存在
  validates :title, presence: true
                    
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def login
    render "accounts/login"
  end

  def signup
    @account = Account.new
  end

  def create
    @account = Account.new(signup_params)
    @account.status = "0" # 用户状态默认为0（激活状态）
    email = signup_params[:email]
    user = Account.find_by(email: email)
    if user.nil?
      if @account.save
        redirect_to accounts_login_path
      else
        render :signup, status: 422
      end
    else
      flash[:error] = "Email has been registered."
      render :signup, status: 422
    end 
  end

  def login_method
    email = params[:email].strip
    pwd = params[:password].strip
    if email.blank? && pwd.blank?
      flash[:error] = "Please enter your email and password."
      render :login , status: 422
    elsif email.blank?
      flash[:error] = "Please enter your email."
      render :login , status: 422
    elsif pwd.blank?
      flash[:error] = "Please enter your password."
      render :login , status: 422
    else
      user = Account.find_by(email: email)
      if user.nil?
         flash[:error] = "User does not exist."
         render :login , status: 404
      else
        if user.authenticate(pwd)
          puts "密码正确"
          session[:account_id] = user.id
          redirect_to articles_path
        else
          flash[:error] = "Incorrect password."
          render :login , status: 401
        end
      end   
    end
  end

  def logout_method
    session.delete(:account_id)
    redirect_to accounts_login_path
  end


    private
      def signup_params
        params.require(:account).permit(:name, :email, :password, :password_confirmation , :role)
      end

      




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :check_login

    def check_login
        if @current_user 
            @current_user 
          else 
            if session[:account_id] 
              @current_user = Account.find_by(id: session[:account_id]) 
            else 
              @current_user = nil 
            end 
            @current_user 
          end
    end

    def login_validity
      unless session[:account_id]
        redirect_to accounts_login_path, alert: "You don't have permission to access this page."
      end
    end
    
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :login_validity, except:[:index]

  def index
    @articles = Article.all.page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
    # @comment = Comment.new
  end  

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.account_id = session[:account_id] 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    puts "!!!!!!!!!!!!#{@article.inspect}"
    @article.destroy
 
    redirect_to articles_path 
  end
  
    private
      def article_params
        params.require(:article).permit(:title, :content)
      end

end

app/controllers/posts_controller.rb
class PostsController < ArticlesController
    
    def create_comment
        account_id = session[:account_id]
        article_id = params[:id]
        post_comment = params[:comment].strip
        puts "!!!!!!!!!!!!!!#{account_id}"
        puts "!!!!!!!!!!!!!!#{article_id}"
        puts "!!!!!!!!!!!!!!#{post_comment}"
        @comment = Comment.new
        @comment.account_id = account_id
        @comment.article_id = article_id
        @comment.content = post_comment
        @comment.parent_id = 0 
        @comment.save
        redirect_to article_path
        # render  json: { success: 'success' }, status: 200
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def login
    # 开发中的代码可以切一个分支出来提交，不要提交到 master
    # username = params[:username]
    # password = params[:password]
    # puts "!!!!!!!!!!!!#{username}"
    # puts "!!!!!!!!!!!!#{password}"
    # if username == "admin" && password == "admin"
    #   redirect_to articles_path
    # end
  end

    def user_params
      
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/accounts/_error_msg.html.erb
<div class="error-msg">
  <h5 style="color: red;">
    <%= pluralize(errors.count, "error") %>
    prohibited this article from being saved:
  </h5>
  <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/accounts/login.html.erb
<div class="container">
    <div class="error-msg">
      <p style="color: red;"><%= flash[:error] %></p> 
    </div>
    <div class="login-form">
        <h1 style="font-size:33px; margin-bottom:8px; color: #4CAF50;">Login</h1>
        <%= form_tag login_method_path, method: :post  do %>
          <div class="mb-3">
            <%= label_tag :email, "Email", class: "form-label fs-5"  %>
            <%= email_field_tag :email, "",placeholder: "xxx.@sina.com", class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= label_tag :password, "Password", class: "form-label fs-5"  %>
            <%= password_field_tag :password, "",placeholder: "Enter password",class: "form-control" %>
          </div>
          <div class="mb-3 st-code">
            <div class="st-left">
              <%= text_field_tag :verification_code, "",placeholder: "Verification Code", class: "form-control" , disabled: true%>
            </div>
            <div class="st-right">
              <div class="st-in-left"></div>
              <div class="st-in-right"></div>
            </div>
          </div>
          <div class="mine-submit">
            <%= submit_tag  "Login", class: "btn btn-outline-success", 
            style: "--bs-btn-padding-y: .5rem; --bs-btn-padding-x: 1.1rem; --bs-btn-font-size: .9rem;" %>
            <%= link_to 'Register', accounts_signup_path, class: "btn btn-outline-secondary" ,
            style: "--bs-btn-padding-y: .46rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .895rem; margin-left: 10px;" %> 
          </div>    
        <% end %> 
    </div>
</div>

<%= stylesheet_link_tag 'accounts_login' %>

app/views/accounts/signup.html.erb
<div class="container">
    <% if @account.errors.any? %>
        <%= render partial: 'error_msg', locals: { errors: @account.errors } %>
    <% end %>
    <p style="color: red;"><%= flash[:error] %></p>    
    <div class="signup-form">
        <h1 style="font-size:33px; margin-bottom:8px; color: #4CAF50;">Registration</h1>
        <%= form_for @account do |f| %>
            <div class="mb-3">
                <%= f.label :name, "Name", class: "form-label fs-5"  %>
                <%= f.text_field :name , placeholder: "Darling, enter your name", class: "form-control"%>
            </div>

            <div class="mb-3">
                <%= f.label :email, "Email", class: "form-label fs-5"  %>
                <%= f.email_field :email, placeholder: "xxx.@sina.com", class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= f.label :password, "Password", class: "form-label fs-5"  %>
                <%= f.password_field :password, placeholder: "Please enter your password", class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= f.label :password_confirmation, "Verification", class: "form-label fs-5"  %>
                <%= f.password_field :password_confirmation, placeholder: "Please enter again", class: "form-control" %>
            </div>

            <div class="mb-3 mb-special">
                <%= f.label :role, "Roles", class: "form-label fs-5", style:"margin-right:8px;"%>
                <%= f.select :role ,options_for_select(Account.roles.map { |key, value| [key, value] })%>
            </div>
            <div id="st-mess" class="form-error"></div>
            <div class="mine-submit">
                <%= f.submit class: "btn btn-outline-success", value: "Register", 
                style: "--bs-btn-padding-y: .46rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .895rem;" %>
                <%= link_to 'Login', accounts_login_path, class: "btn btn-outline-secondary", 
                style: "--bs-btn-padding-y: .46rem; --bs-btn-padding-x: 1.1rem; --bs-btn-font-size: .895rem; margin-left: 10px;"%>    
          </div>    
            </div>    
        <% end %> 
    </div>
</div>


<%= stylesheet_link_tag 'accounts_signup' %>

app/views/articles/_form.html.erb
 <div class="mb-3">
  <%= f.label :title, "Title", class: "form-label fs-5" %>
  <%= f.text_field :title, placeholder: "Please enter your title", class: "form-control"%>
  <div id="emailHelp" class="form-text">We will share your article in our blog.</div>
</div>
<div class="mb-3">
  <%= f.label :content, "Content", class: "form-label fs-5" %>
  <%= f.text_area :content, placeholder: "Please enter your articles", class: "form-control"%>
</div>

app/views/articles/edit.html.erb
<div class="content">
  <div class="row">
    <div class="content-main">
      <div class="st-content-main">
        <h3 style="margin-bottom: 20px;">UPDATE YOUR ARTICLES</h3>

        <%= form_for :article, url: articles_path  do |f| %>
        <%= render 'form', f: f %>
        <%= f.submit class: "btn btn-primary", value: "Update Content"%>
        <%= link_to 'Cancel', articles_path, class: "btn btn-primary", style: 'margin-left: 10px;'%> 
      <% end %>
      </div>
    </div>
  </div>
  
</div>
<%= stylesheet_link_tag 'articles_new' %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="box article-container">
      <div class="container-main-left">
        
        <div id="carouselExampleIndicators" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: First slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#555" dy=".3em">First slide</text></svg>
            </div>
            <div class="carousel-item">
              <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Second slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#666"></rect><text x="50%" y="50%" fill="#444" dy=".3em">Second slide</text></svg>
            </div>
            <div class="carousel-item">
              <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Third slide" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#555"></rect><text x="50%" y="50%" fill="#333" dy=".3em">Third slide</text></svg>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      
      </div>
      <div class="container-main-right cm-style">
        <div class="cmr-in" style="display: flex;">
            <span class="span1" style="font-weight: bold; color: #1e9c10; font-size: 18px;">Article Category</span>
            <span class="span2" style="font-size: 15px; color: #312f2f75; padding-top:2px; margin-left: 5px;">#Today's Tweets</span>
        </div>

        <h1 style="font-size: 35px;">TODO</h1>
        
      </div>
   </div>
  </div>
  <div class="row">
    <div class="box inverted-main-grid">
      <table>
          <% @articles.each do |article| %>
            <tr>
              <div class="show-main-acticles">
                <h4 style="margin-bottom: 20px;"><%= article.title %></h4>
                <p style="margin-bottom: 10px;"><%= article.content %></p>
                <div class="show-acticles-in">
                  <div class="div1"><%= image_tag("time.svg") %> <%= article.created_at.strftime("%Y-%m-%d") %> </div>
                  <div class="div2"><%= image_tag("visit.svg") %> Number of visits</div>
                  <div class="div3"><%= image_tag("reply.svg") %> Number of reviews</div>
                  <div class="div4"><%= image_tag("category.svg") %> Article Category</div>
                  <div class="div5"><%= image_tag("user.svg") %> <%= article.account.name %> </div>
                  <div class="div6">
                  <%= link_to 'Details', article_path(article), class: 'btn btn-outline-success', style:"--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %>
                  <%= link_to 'Edits', edit_article_path(article), class: 'btn btn-outline-warning', style:"--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %>
                  </div>
                </div>
              </div>
            </tr>
          <% end %>
        </table>
        <div class="show-main-footer">
          <%= paginate @articles, theme: 'bootstrap-5' , pagination_class: "pagination-sm flex-wrap justify-content-center" %>
      </div>
      </div>


  </div>
  <%
=begin%>
 <div class="row">
    <div class="box divider">
      <div class="separator"></div>
    
    </div>
  </div> 
<%
=end%>
  <div class="row">
    <div class="box main-grid"></div>
  </div>
</div>


<style>
.show-main-footer {
  margin-top: 30px;
  display: flex;
  justify-content: center;
}

.page-link {
  color: black; /* 将颜色替换为您想要的颜色 */
}



</style>


<%= stylesheet_link_tag 'articles_index' %>

app/views/articles/new.html.erb
<div class="content">
  <div class="row">
    <div class="content-main">
      <div class="st-content-main">
        <h3 style="margin-bottom: 20px;">SHARE YOUR ARTICLES</h3>

        <%= form_for :article, url: articles_path  do |f| %>
        <%= render 'form', f: f %>
        <%= f.submit class: "btn btn-primary", value: "Add Content"%>
      <% end %>
      </div>
    </div>
  </div>
  
</div>
<%= stylesheet_link_tag 'articles_new' %>

app/views/articles/show.html.erb
<div class="content">
  <div class="row">
    <div class="show-content-main">
      <div class="sh-main">
        <h1><%= @article.title %></h1>
        <p><%= @article.content %></p>
        <div class="sf-main">
          <nav class="st-nav">
            <%= link_to 'Edits', edit_article_path(@article), class: 'btn btn-outline-warning', style:"--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %>
          </nav>
          <nav class="st-nav">
          <%= link_to 'Delete', article_path(@article), data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?'},  class: 'btn btn-outline-danger', style:"--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %>
          </nav>
            <nav class="st-nav">
            <%= link_to 'Back', articles_path, class: 'btn btn-outline-success', style:"--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %>
          </nav>
        </div>
      </div>

    </div>
  </div>

</div>
<div class="comment">
  <div class="row">
    <div class="show-comment-main">
      <div class="scm-comment">
        <h4 class="st-underline">COMMENTS</h4>
        <div class="comment-content">
          <div class="submit-content">
            <%= form_tag create_comment_path, method: :post  do %>
              <div class="st-in">
                <%= text_area_tag :comment, "",placeholder: "Please enter your comments", class: "form-control", rows: 4%>
              </div>
              <div id="st-exception" class="alert alert-warning" role="alert" style="display: none;">
                Comment content is empty!
              </div>  
              <div class="st-in st-submit">
                <%= submit_tag  "Add Comment", id: "submit-comment", class: "btn btn-outline-success", 
                style: "--bs-btn-padding-y: .5rem; --bs-btn-padding-x: 1.1rem; --bs-btn-font-size: .9rem;" %>
              </div>
            <% end %>
              <div class="st-separator"></div>
          </div>
        </div>

        <div class="show-comment">
          <div class="show-in">
            <div class="card border-success mb-3" style="width: 24rem;">
              <div class="card-body text-success">
                <p class="card-text" style="font-size: 10px;">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <div class="st-card-in">
                  <div class="card-content">
                    <h6>Name | 2023-7-10</h6>
                  </div>
                  <div class="card-content st-other">
                    <button type="button" class="btn btn-outline-info"
                            style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                            Reply
                    </button>
                  </div>
                <div>
              </div>
            </div>
          </div>
        </div>


      <div>

    </div> 
  </div>     
</div>



<%= stylesheet_link_tag 'articles_show' %>

<script>
document.getElementById("submit-comment").addEventListener("click", function(event) {
  const textarea = document.getElementById('comment');
  const commentValue = textarea.value.trim();
  if (commentValue === '') {
    document.getElementById('st-exception').style.display = 'block';
    event.preventDefault(); // 阻止表单的默认提交行为
  } 
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      body {
            background-color: #f5f5f5;
        }

      footer {
          padding: 10px;
          display: flex;
          justify-content: center; /* 水平方向居中对齐 */
          align-items: center; /* 垂直方向居中对齐 */
      }

    </style>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
          <a class="navbar-brand" href="#">MYBLOG</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
              <%= link_to 'HOME', articles_path, class: 'nav-link active' %>
              </li>
              <li class="nav-item">
              <%= link_to 'ARTICLES', new_article_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="#">ABOUT</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="#">ARCHIVES</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="#">TAGS</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="#">MESSAGE</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="#">TRANSLATION</a>
              </li>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  PHOTOALBUMS
              </a>
              <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
              </li>
          </ul>
          

          <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="SEARCH" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">SEARCH</button>
          </form>
          <% unless check_login %>
            <span class="navbar-text" style="margin-left: 10px; " >
                <%= link_to 'LOGIN', accounts_login_path, class: 'btn btn-light' %>
            </span>
          <% else %>
            <span class="navbar-text" style="margin-left: 10px; " >
                <%= link_to 'LOGOUT', logout_method_path, class: 'btn btn-light' %>
            </span>
            <div><span style="margin-left: 10px; font-weight: bold;">User: <%= check_login.name %> </span></div>
          <% end %>
          </div>

      </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>

    <footer class="blockquote-footer">
      Basic Webpage. &copy; 2023  All rights reserved.
    </footer>  
  </body>
</html>

app/views/shared/_table.html.erb
 <div class="mb-3">
  <%= f.label :title, "Title", class: "form-label fs-5" %>
  <%= f.text_field :title, placeholder: "Please enter your title", class: "form-control"%>
  <div id="emailHelp" class="form-text">We will share your article in our blog.</div>
</div>
<div class="mb-3">
  <%= f.label :content, "Content", class: "form-label fs-5" %>
  <%= f.text_area :content, placeholder: "Please enter your articles", class: "form-control"%>
</div>